# Base configs
baseurl: "http://www.hemmul.com/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography"
subtitle: "playing around"
author: "Alex Bijamov"
header:
 title: "Photography"
 subtitle: "by Alex Bijamov"
footer:
 name: "Thanks for stopping by"
social_urls:
  github: "https://github.com/hammerhaifisch/"
